language: php

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit

before_deploy:
  # make sure git tests do not complain about user/email not being set
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
  - curl -L -o box.phar https://github.com/humbug/box/releases/download/3.0.0-RC.0/box.phar
  - php -d phar.readonly=0 box.phar compile

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: bin/vendor-prune.phar
  skip_cleanup: true
  on:
    tags: true
    php:  '7.1'